name: Gerar PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Gerar PDF
        run: |
          # Comando para gerar o PDF aqui
          make gerar-pdf
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: usm_tutorial.pdf
          path: usm-tutoria/usm_tutorial.pdf

