name: Gerar-PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Checkout com permissão para commitar mudanças
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Tectonic
        uses: wtfjoke/setup-tectonic@v3

      - name: Executar Makefile
        run: |
          make

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        id: upload
        with:
          name: usm_tutorial.pdf
          path: usm_tutorial.pdf
