name: Gerar PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Tectonic
        uses: wtfjoke/setup-tectonic@v3
      - name: Executar Makefile
        run: |
          make gerar-pdf
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: usm_tutorial.pdf
          path: usm_tutorial.pdf

